name: r_scan_example
description: Demonstrates how to use the r_scan plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.7.3
  # 权限请求
  permission_handler: ^6.1.1

  r_scan:
    path: ../

flutter:
  uses-material-design: true

  assets:
   - images/qrCode.png
