name: r_scan
description: A flutter plugin about qr code scan,it can scan from file, url, memory and camera qr code.
version: 0.1.5
homepage: https://github.com/AlexV525/r_scan

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.rhyme.r_scan
        pluginClass: RScanPlugin
      ios:
        pluginClass: RScanPlugin
